# Importing all the necessary libraries

In [285]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Reading the Dataset

In [286]:
df = pd.read_csv("Football_stats_test.csv")
print(df)

      S.No             Player Nation   Pos          Squad            Comp  \
0        1   Brenden Aaronson    USA  MFFW   Leeds United  Premier League
1        2   Yunis Abdelhamid    MAR    DF          Reims         Ligue 1
2        3      Himad Abdelli    FRA    MF         Angers         Ligue 1
3        4  Salis Abdul Samed    GHA    MF           Lens         Ligue 1
4        5    Laurent Abergel    FRA    MF        Lorient         Ligue 1
...    ...                ...    ...   ...            ...             ...
2234  2235       Nadir Zortea    ITA    DF       Atalanta         Serie A
2235  2236         Kurt Zouma    FRA    DF       West Ham  Premier League
2236  2237      Igor Zubeldia    ESP    DF  Real Sociedad         La Liga
2237  2238   Martín Zubimendi    ESP    MF  Real Sociedad         La Liga
2238  2239   Szymon ?urkowski    POL    MF     Fiorentina         Serie A

      Age  Born  MP  Starts  ...   Off   Crs  TklW  PKwon  PKcon   OG  Recov  \
0      21  2000   7       7  ...  0.47  1.25  1.09    0.0    0.0  0.0   5.78
1      35  1987  10      10  ...  0.00  0.20  1.30    0.0    0.0  0.0   8.50
2      22  1999   3       0  ...  0.00  0.00  0.00    0.0    0.0  0.0  10.00
3      22  2000   9       9  ...  0.00  0.44  1.11    0.0    0.0  0.0   7.89
4      29  1993   9       9  ...  0.00  0.11  2.41    0.0    0.0  0.0   6.67
...   ...   ...  ..     ...  ...   ...   ...   ...    ...    ...  ...    ...
2234   23  1999   5       0  ...  0.00  3.64  0.91    0.0    0.0  0.0  10.90
2235   27  1994   8       8  ...  0.00  0.00  0.38    0.0    0.0  0.0   7.38
2236   25  1997   6       5  ...  0.00  0.00  1.11    0.0    0.0  0.0  10.70
2237   23  1999   7       7  ...  0.14  0.29  2.00    0.0    0.0  0.0   9.71
2238   25  1997   2       0  ...  0.00  0.00  0.00    0.0    0.0  0.0  10.00

      AerWon  AerLost  AerWon%
0       0.47     2.66     15.0
1       2.00     0.70     74.1
2       0.00     3.33      0.0
3       0.44     0.78     36.4
4       0.57     0.34     62.5
...      ...      ...      ...
2234    0.91     0.91     50.0
2235    3.38     0.38     90.0
2236    1.78     2.44     42.1
2237    3.29     0.71     82.1
2238    0.00     5.00      0.0

[2239 rows x 143 columns]

## La Liga

#### Making a DataFrame of only La Liga players

In [287]:
a = df.loc[df.Comp == "La Liga"]
print(a)
a.to_csv("La_liga.csv")

      S.No            Player Nation Pos          Squad     Comp  Age  Born  \
10      11      Marcos Acuña    ARG  DF        Sevilla  La Liga   30  1991
24      25     Álvaro Aguado    ESP  MF     Valladolid  La Liga   26  1996
29      30      Joseph Aidoo    GHA  DF     Celta Vigo  La Liga   27  1995
37      38     Sergio Akieme    ESP  DF        Almería  La Liga   24  1997
39      40     Paul Akouokou    CIV  MF          Betis  La Liga   24  1997
...    ...               ...    ...  ..            ...      ...  ...   ...
2196  2197    Jawad El Yamiq    MAR  DF     Valladolid  La Liga   30  1992
2211  2212     Joseba Zaldúa    ESP  DF          Cádiz  La Liga   30  1992
2219  2220      Oier Zarraga    ESP  MF  Athletic Club  La Liga   23  1999
2236  2237     Igor Zubeldia    ESP  DF  Real Sociedad  La Liga   25  1997
2237  2238  Martín Zubimendi    ESP  MF  Real Sociedad  La Liga   23  1999

      MP  Starts  ...   Off   Crs  TklW  PKwon  PKcon   OG  Recov  AerWon  \
10     6       5  ...  0.00  4.67  2.44    0.0   0.22  0.0   8.44    2.00
24     6       5  ...  0.00  0.68  0.91    0.0   0.23  0.0  10.20    0.23
29     7       7  ...  0.00  0.14  1.29    0.0   0.00  0.0   9.86    1.43
37     8       8  ...  0.00  2.25  1.63    0.0   0.00  0.0   7.63    0.50
39     4       1  ...  0.00  0.00  2.31    0.0   0.00  0.0   9.23    0.00
...   ..     ...  ...   ...   ...   ...    ...    ...  ...    ...     ...
2196   3       2  ...  0.00  0.00  2.14    0.0   0.00  0.0   6.43    2.14
2211   7       5  ...  0.19  1.35  0.58    0.0   0.00  0.0   7.50    2.12
2219   5       0  ...  0.00  2.50  0.00    0.0   0.00  0.0  10.80    1.67
2236   6       5  ...  0.00  0.00  1.11    0.0   0.00  0.0  10.70    1.78
2237   7       7  ...  0.14  0.29  2.00    0.0   0.00  0.0   9.71    3.29

      AerLost  AerWon%
10       0.89     69.2
24       0.68     25.0
29       2.00     41.7
37       1.00     33.3
39       1.54      0.0
...       ...      ...
2196     0.00    100.0
2211     1.73     55.0
2219     1.67     50.0
2236     2.44     42.1
2237     0.71     82.1

[466 rows x 143 columns]

#### Deleting S.No column from DataFrame

In [288]:
b = a.drop('S.No', axis = 1)
print(b)

                Player Nation Pos          Squad     Comp  Age  Born  MP  \
10        Marcos Acuña    ARG  DF        Sevilla  La Liga   30  1991   6
24       Álvaro Aguado    ESP  MF     Valladolid  La Liga   26  1996   6
29        Joseph Aidoo    GHA  DF     Celta Vigo  La Liga   27  1995   7
37       Sergio Akieme    ESP  DF        Almería  La Liga   24  1997   8
39       Paul Akouokou    CIV  MF          Betis  La Liga   24  1997   4
...                ...    ...  ..            ...      ...  ...   ...  ..
2196    Jawad El Yamiq    MAR  DF     Valladolid  La Liga   30  1992   3
2211     Joseba Zaldúa    ESP  DF          Cádiz  La Liga   30  1992   7
2219      Oier Zarraga    ESP  MF  Athletic Club  La Liga   23  1999   5
2236     Igor Zubeldia    ESP  DF  Real Sociedad  La Liga   25  1997   6
2237  Martín Zubimendi    ESP  MF  Real Sociedad  La Liga   23  1999   7

      Starts  Min  ...   Off   Crs  TklW  PKwon  PKcon   OG  Recov  AerWon  \
10         5  405  ...  0.00  4.67  2.44    0.0   0.22  0.0   8.44    2.00
24         5  395  ...  0.00  0.68  0.91    0.0   0.23  0.0  10.20    0.23
29         7  630  ...  0.00  0.14  1.29    0.0   0.00  0.0   9.86    1.43
37         8  720  ...  0.00  2.25  1.63    0.0   0.00  0.0   7.63    0.50
39         1  117  ...  0.00  0.00  2.31    0.0   0.00  0.0   9.23    0.00
...      ...  ...  ...   ...   ...   ...    ...    ...  ...    ...     ...
2196       2  125  ...  0.00  0.00  2.14    0.0   0.00  0.0   6.43    2.14
2211       5  466  ...  0.19  1.35  0.58    0.0   0.00  0.0   7.50    2.12
2219       0  106  ...  0.00  2.50  0.00    0.0   0.00  0.0  10.80    1.67
2236       5  402  ...  0.00  0.00  1.11    0.0   0.00  0.0  10.70    1.78
2237       7  630  ...  0.14  0.29  2.00    0.0   0.00  0.0   9.71    3.29

      AerLost  AerWon%
10       0.89     69.2
24       0.68     25.0
29       2.00     41.7
37       1.00     33.3
39       1.54      0.0
...       ...      ...
2196     0.00    100.0
2211     1.73     55.0
2219     1.67     50.0
2236     2.44     42.1
2237     0.71     82.1

[466 rows x 142 columns]

### Average age of players

In [289]:
a= int(b["Age"].mean())
print("Average age of player is: ", a)

Average age of player is:  26

#### Oldest player in the league

In [290]:
a = b.loc[b["Age"].idxmax()]
print(a,'\n')
print("Name of the oldest player: ", a['Player'],"\n")
print("Age of the oldest player: ", a['Age'])

Player     Joaquín
Nation         ESP
Pos           FWMF
Squad        Betis
Comp       La Liga
            ...
OG             0.0
Recov         10.0
AerWon         0.0
AerLost        0.0
AerWon%        0.0
Name: 1025, Length: 142, dtype: object

Name of the oldest player:  Joaquín

Age of the oldest player:  41

#### Yougest player in the league.

In [291]:
a = b.loc[b["Age"].idxmin()]
print(a,'\n')
print("Name of the oldest player: ", a['Player'])
print("Age of the oldest player: ", a['Age'])

Player     Javier Llabrés
Nation                  0
Pos                    FW
Squad            Mallorca
Comp              La Liga
                ...
OG                    0.0
Recov                 5.0
AerWon                0.0
AerLost               5.0
AerWon%               0.0
Name: 1226, Length: 142, dtype: object

Name of the oldest player:  Javier Llabrés
Age of the oldest player:  0

###### Since Age of the player 0 is not possible, this data is false.

##### Therefore removing this data from the DataFrame.

In [292]:
c = b.drop(1226)
print(c)

                Player Nation Pos          Squad     Comp  Age  Born  MP  \
10        Marcos Acuña    ARG  DF        Sevilla  La Liga   30  1991   6
24       Álvaro Aguado    ESP  MF     Valladolid  La Liga   26  1996   6
29        Joseph Aidoo    GHA  DF     Celta Vigo  La Liga   27  1995   7
37       Sergio Akieme    ESP  DF        Almería  La Liga   24  1997   8
39       Paul Akouokou    CIV  MF          Betis  La Liga   24  1997   4
...                ...    ...  ..            ...      ...  ...   ...  ..
2196    Jawad El Yamiq    MAR  DF     Valladolid  La Liga   30  1992   3
2211     Joseba Zaldúa    ESP  DF          Cádiz  La Liga   30  1992   7
2219      Oier Zarraga    ESP  MF  Athletic Club  La Liga   23  1999   5
2236     Igor Zubeldia    ESP  DF  Real Sociedad  La Liga   25  1997   6
2237  Martín Zubimendi    ESP  MF  Real Sociedad  La Liga   23  1999   7

      Starts  Min  ...   Off   Crs  TklW  PKwon  PKcon   OG  Recov  AerWon  \
10         5  405  ...  0.00  4.67  2.44    0.0   0.22  0.0   8.44    2.00
24         5  395  ...  0.00  0.68  0.91    0.0   0.23  0.0  10.20    0.23
29         7  630  ...  0.00  0.14  1.29    0.0   0.00  0.0   9.86    1.43
37         8  720  ...  0.00  2.25  1.63    0.0   0.00  0.0   7.63    0.50
39         1  117  ...  0.00  0.00  2.31    0.0   0.00  0.0   9.23    0.00
...      ...  ...  ...   ...   ...   ...    ...    ...  ...    ...     ...
2196       2  125  ...  0.00  0.00  2.14    0.0   0.00  0.0   6.43    2.14
2211       5  466  ...  0.19  1.35  0.58    0.0   0.00  0.0   7.50    2.12
2219       0  106  ...  0.00  2.50  0.00    0.0   0.00  0.0  10.80    1.67
2236       5  402  ...  0.00  0.00  1.11    0.0   0.00  0.0  10.70    1.78
2237       7  630  ...  0.14  0.29  2.00    0.0   0.00  0.0   9.71    3.29

      AerLost  AerWon%
10       0.89     69.2
24       0.68     25.0
29       2.00     41.7
37       1.00     33.3
39       1.54      0.0
...       ...      ...
2196     0.00    100.0
2211     1.73     55.0
2219     1.67     50.0
2236     2.44     42.1
2237     0.71     82.1

[465 rows x 142 columns]

##### Now finding the youngest player in the league

In [293]:
a = c.loc[c["Age"].idxmin()]
print(a,'\n')
print("Name of the youngest player: ", a['Player'])
print("Age of the youngest player: ", a['Age'])

Player     Wassim Boullif
Nation                ESP
Pos                    DF
Squad            Espanyol
Comp              La Liga
                ...
OG                    0.0
Recov                 2.5
AerWon                2.5
AerLost               2.5
AerWon%              50.0
Name: 284, Length: 142, dtype: object

Name of the youngest player:  Wassim Boullif
Age of the youngest player:  17

#### Top 5 Goal Scorers.

In [295]:
Goal_scorer = c.nlargest(5, ['Goals'])
g_a = Goal_scorer['Player']
#print("Top 5 Players with most Goal_scorers: \n", g_a,"\n")

g_b =  Goal_scorer['Squad']
#print("Respective Clubs: \n",g_a,"\n")

g_c = Goal_scorer['Pos']
#print("Respective Positions: \n", g_c,"\n")

g_d = Goal_scorer["Goals"]

g_e = Goal_scorer["Nation"]

Goal_scorer_df = pd.concat([g_a,g_b,g_c,g_d,g_e],axis=1)
print(Goal_scorer_df)

                  Player            Squad Pos  Goals Nation
889       Gorka Guruzeta    Athletic Club  FW   1.67    ESP
1211  Robert Lewandowski        Barcelona  FW   1.50    POL
463         Ángel Correa  Atlético Madrid  FW   1.20    ARG
1816          Umar Sadiq    Real Sociedad  FW   1.11    NGA
981       Borja Iglesias            Betis  FW   1.00    ESP

#### Top 5 players with most Assists.

In [296]:
assist = c.nlargest(5, ['Assists'])
aa_a = assist['Player']
#print("Top 5 Players with most assists: \n", aa_a,"\n")

aa_b =  assist['Squad']
#print("Respective Clubs: \n",aa_a,"\n")

aa_c =  assist["Nation"]

#print("Respective Positions: \n", aa_c,"\n")

aa_d = assist['Pos']

aa_e = assist["Assists"]

assist_df = pd.concat([aa_a,aa_b,aa_c,aa_d,aa_e],axis=1)
print(assist_df)

               Player          Squad Nation   Pos  Assists
1449     Jon Morcillo  Athletic Club    ESP  FWDF     2.50
702         Ansu Fati      Barcelona    ESP    FW     1.20
1379   Gonzalo Melero        Almería    ESP    MF     1.00
671      Adri Embarba        Almería    ESP    FW     0.91
57    Mohamed Ali Cho  Real Sociedad    FRA    FW     0.80

#### Top 5 Players with most Dribbles completed successfully.

In [297]:
Dribbles = c.nlargest(5, ['DriSucc'])
d_a = Dribbles['Player']
#print("Top 5 Players with most Dribbless: \n", d_a,"\n")

d_b =  Dribbles['Squad']
#print("Respective Clubs: \n",d_a,"\n")

d_c =  Dribbles["Nation"]

#print("Respective Positions: \n", d_c,"\n")

d_d = Dribbles['Pos']

d_e = Dribbles["DriSucc"]

Dribbles_df = pd.concat([d_a,d_b,d_c,d_d,d_e],axis=1)
print(Dribbles_df)

               Player       Squad Nation   Pos  DriSucc
379            Casals      Girona    ESP  FWMF     20.0
1091           Kenedy  Valladolid    BRA    MF     10.0
1634  Francisco Perez    Valencia    ESP  DFFW     10.0
1770  Ángel Rodríguez    Mallorca    ESP    MF     10.0
109    Roberto Arroyo  Valladolid    ESP    MF      5.0

#### Top 5 players most Tackles.

In [298]:
tackle = c.nlargest(5, ['Tkl'])
t_a = tackle['Player']
#print("Top 5 Players with most tackles: \n", t_a,"\n")

t_b =  tackle['Squad']
#print("Respective Clubs: \n",t_a,"\n")

t_c = tackle["Nation"]
#print("Respective Positions: \n", t_c,"\n")

t_d = tackle['Pos']

t_e = tackle["Tkl"]

tackle_df = pd.concat([t_a,t_b,t_c,t_d,t_e],axis=1)
print(tackle_df)

              Player       Squad Nation   Pos    Tkl
1254      Pol Lozano    Espanyol    ESP    MF  10.00
1455     Loren Morón       Betis    ESP  FWMF  10.00
977     Pablo Ibáñez     Osasuna    ESP  MFFW   6.67
1114   Luca Koleosho    Espanyol    CAN  DFMF   6.67
1420  Óscar Mingueza  Celta Vigo    ESP    DF   6.67

#### Top 5 players with the most red cards

In [299]:
red_card = c.nlargest(5, ['CrdR'])
rc_a = red_card['Player']
#print("Top 5 Players with most red_cards: \n", rc_a,"\n")

rc_b =  red_card['Squad']
#print("Respective Clubs: \n",rc_a,"\n")

rc_c = red_card["Nation"]

#print("Respective Positions: \n", rc_c,"\n")

rc_d = red_card['Pos']

rc_e = red_card["CrdR"]


red_card_df = pd.concat([rc_a,rc_b,rc_c,rc_d,rc_e],axis=1)
print(red_card_df)

              Player            Squad Nation Pos   CrdR
2124   Gonzalo Verdú            Elche    ESP  DF  10.00
940    Ander Herrera    Athletic Club    ESP  MF   1.11
935    Mario Hermoso  Atlético Madrid    ESP  DF   0.77
1411      Luis Milla           Getafe    ESP  MF   0.77
2196  Jawad El Yamiq       Valladolid    MAR  DF   0.71

#### Player with most Own goals.

In [303]:
OG = c.loc[c["OG"].idxmax()]
#print(OG)
print (OG["Player"])

Nicolás Ezequiel Fernández

#### Pie chart of the age of the players

In [294]:
a = (c["Age"])
h = a.tolist()
#s = set(b)
#print(s)

#print(b,"\n")
for i in h:
    count = h.count(i)
    a = i, count
    print(a)
    #b = set(a)
    #print(b)

    
    
#plt.bar(i, count, width = 0.4)
plt.show

(30, 42)
(26, 33)
(27, 35)
(24, 29)
(24, 29)
(30, 42)
(23, 25)
(33, 24)
(37, 3)
(31, 35)
(27, 35)
(24, 29)
(20, 20)
(23, 25)
(18, 7)
(22, 26)
(31, 35)
(22, 26)
(27, 35)
(28, 29)
(28, 29)
(27, 35)
(27, 35)
(23, 25)
(19, 12)
(24, 29)
(33, 24)
(26, 33)
(35, 8)
(33, 24)
(28, 29)
(26, 33)
(26, 33)
(30, 42)
(21, 25)
(18, 7)
(30, 42)
(30, 42)
(25, 43)
(25, 43)
(20, 20)
(31, 35)
(32, 14)
(27, 35)
(23, 25)
(34, 14)
(32, 14)
(27, 35)
(32, 14)
(21, 25)
(22, 26)
(26, 33)
(17, 2)
(31, 35)
(26, 33)
(31, 35)
(23, 25)
(30, 42)
(31, 35)
(23, 25)
(34, 14)
(31, 35)
(27, 35)
(19, 12)
(21, 25)
(31, 35)
(30, 42)
(34, 14)
(29, 32)
(34, 14)
(26, 33)
(26, 33)
(20, 20)
(29, 32)
(30, 42)
(30, 42)
(17, 2)
(30, 42)
(24, 29)
(27, 35)
(27, 35)
(35, 8)
(26, 33)
(28, 29)
(24, 29)
(26, 33)
(23, 25)
(22, 26)
(28, 29)
(30, 42)
(23, 25)
(24, 29)
(26, 33)
(22, 26)
(31, 35)
(29, 32)
(27, 35)
(23, 25)
(34, 14)
(21, 25)
(30, 42)
(20, 20)
(30, 42)
(25, 43)
(23, 25)
(26, 33)
(28, 29)
(28, 29)
(31, 35)
(21, 25)
(25, 43)
(28, 29)
(25, 43)
(22, 26)
(28, 29)
(20, 20)
(30, 42)
(30, 42)
(25, 43)
(21, 25)
(22, 26)
(27, 35)
(22, 26)
(30, 42)
(28, 29)
(28, 29)
(30, 42)
(30, 42)
(25, 43)
(33, 24)
(30, 42)
(33, 24)
(26, 33)
(22, 26)
(20, 20)
(36, 5)
(29, 32)
(19, 12)
(33, 24)
(29, 32)
(33, 24)
(25, 43)
(22, 26)
(31, 35)
(29, 32)
(24, 29)
(26, 33)
(33, 24)
(26, 33)
(35, 8)
(32, 14)
(32, 14)
(29, 32)
(24, 29)
(18, 7)
(27, 35)
(29, 32)
(25, 43)
(29, 32)
(32, 14)
(28, 29)
(21, 25)
(23, 25)
(36, 5)
(29, 32)
(30, 42)
(27, 35)
(24, 29)
(31, 35)
(24, 29)
(26, 33)
(28, 29)
(34, 14)
(30, 42)
(27, 35)
(25, 43)
(20, 20)
(21, 25)
(26, 33)
(26, 33)
(31, 35)
(31, 35)
(25, 43)
(36, 5)
(31, 35)
(30, 42)
(25, 43)
(22, 26)
(27, 35)
(26, 33)
(25, 43)
(21, 25)
(27, 35)
(31, 35)
(21, 25)
(27, 35)
(33, 24)
(33, 24)
(33, 24)
(29, 32)
(24, 29)
(19, 12)
(24, 29)
(24, 29)
(29, 32)
(32, 14)
(23, 25)
(30, 42)
(21, 25)
(24, 29)
(41, 1)
(25, 43)
(28, 29)
(32, 14)
(30, 42)
(32, 14)
(29, 32)
(31, 35)
(31, 35)
(22, 26)
(18, 7)
(21, 25)
(20, 20)
(26, 33)
(25, 43)
(32, 14)
(23, 25)
(30, 42)
(18, 7)
(29, 32)
(23, 25)
(32, 14)
(21, 25)
(30, 42)
(24, 29)
(30, 42)
(21, 25)
(24, 29)
(20, 20)
(25, 43)
(31, 35)
(29, 32)
(31, 35)
(29, 32)
(26, 33)
(33, 24)
(34, 14)
(25, 43)
(27, 35)
(26, 33)
(33, 24)
(40, 1)
(26, 33)
(29, 32)
(23, 25)
(27, 35)
(35, 8)
(23, 25)
(27, 35)
(25, 43)
(27, 35)
(31, 35)
(26, 33)
(22, 26)
(28, 29)
(30, 42)
(25, 43)
(26, 33)
(34, 14)
(33, 24)
(34, 14)
(27, 35)
(29, 32)
(31, 35)
(19, 12)
(31, 35)
(29, 32)
(33, 24)
(33, 24)
(25, 43)
(24, 29)
(28, 29)
(24, 29)
(25, 43)
(27, 35)
(26, 33)
(33, 24)
(24, 29)
(28, 29)
(30, 42)
(19, 12)
(23, 25)
(25, 43)
(22, 26)
(32, 14)
(37, 3)
(30, 42)
(30, 42)
(24, 29)
(24, 29)
(23, 25)
(25, 43)
(31, 35)
(29, 32)
(24, 29)
(29, 32)
(30, 42)
(25, 43)
(19, 12)
(28, 29)
(18, 7)
(24, 29)
(29, 32)
(25, 43)
(28, 29)
(19, 12)
(32, 14)
(27, 35)
(29, 32)
(20, 20)
(36, 5)
(37, 3)
(20, 20)
(27, 35)
(20, 20)
(24, 29)
(25, 43)
(29, 32)
(23, 25)
(28, 29)
(28, 29)
(28, 29)
(20, 20)
(21, 25)
(28, 29)
(18, 7)
(29, 32)
(27, 35)
(22, 26)
(33, 24)
(20, 20)
(33, 24)
(31, 35)
(26, 33)
(19, 12)
(31, 35)
(31, 35)
(24, 29)
(20, 20)
(25, 43)
(34, 14)
(27, 35)
(31, 35)
(19, 12)
(35, 8)
(31, 35)
(21, 25)
(25, 43)
(32, 14)
(30, 42)
(26, 33)
(23, 25)
(29, 32)
(24, 29)
(21, 25)
(22, 26)
(31, 35)
(26, 33)
(34, 14)
(21, 25)
(25, 43)
(20, 20)
(27, 35)
(27, 35)
(22, 26)
(21, 25)
(29, 32)
(22, 26)
(30, 42)
(25, 43)
(30, 42)
(22, 26)
(35, 8)
(24, 29)
(34, 14)
(28, 29)
(21, 25)
(21, 25)
(31, 35)
(21, 25)
(29, 32)
(26, 33)
(30, 42)
(29, 32)
(25, 43)
(25, 43)
(31, 35)
(31, 35)
(22, 26)
(25, 43)
(22, 26)
(25, 43)
(30, 42)
(25, 43)
(22, 26)
(31, 35)
(25, 43)
(36, 5)
(28, 29)
(25, 43)
(30, 42)
(23, 25)
(30, 42)
(25, 43)
(29, 32)
(26, 33)
(33, 24)
(23, 25)
(22, 26)
(35, 8)
(34, 14)
(35, 8)
(28, 29)
(27, 35)
(22, 26)
(29, 32)
(30, 42)
(21, 25)
(22, 26)
(27, 35)
(25, 43)
(33, 24)
(28, 29)
(21, 25)
(34, 14)
(20, 20)
(25, 43)
(19, 12)
(28, 29)
(22, 26)
(20, 20)
(26, 33)
(25, 43)
(24, 29)
(19, 12)
(31, 35)
(20, 20)
(21, 25)
(33, 24)
(29, 32)
(33, 24)
(27, 35)
(27, 35)
(27, 35)
(25, 43)
(23, 25)
(26, 33)
(28, 29)
(20, 20)
(33, 24)
(30, 42)
(30, 42)
(23, 25)
(25, 43)
(23, 25)